ALTER TABLE risk_config
    ADD COLUMN IF NOT EXISTS broker_limit_usage DOUBLE PRECISION NOT NULL DEFAULT 0.95,
    ADD COLUMN IF NOT EXISTS min_order_cash_buffer BIGINT NOT NULL DEFAULT 100,
    ADD COLUMN IF NOT EXISTS allow_min_position_size_upscale BOOLEAN NOT NULL DEFAULT FALSE;
