ALTER TABLE portfolio_snapshots
    ADD COLUMN IF NOT EXISTS blocked_cash DECIMAL(20, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS available_cash DECIMAL(20, 4) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS currency VARCHAR(10) NOT NULL DEFAULT 'rub';
